env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - eslint:recommended
  - react-app
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  react/jsx-filename-extension: [0, { "extensions": [".js", ".jsx"] }],
  react/prop-types: 0,
  import/extensions: 0,
  import/no-unresolved: 0,
  # https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/function-component-definition.md
  react/function-component-definition: 0,
  no-param-reassign: 1,
  import/prefer-default-export: 1,
  consistent-return: 1,
  react/jsx-no-useless-fragment: 0,
  react/jsx-props-no-spreading: 1,
  react-hooks/exhaustive-deps: 0,
  no-trailing-spaces: 1,
  react/jsx-indent: 1,
  react/jsx-first-prop-new-line: 1,
  react/jsx-max-props-per-line: 1,
  react/jsx-wrap-multilines: 1,
  import/named: 1,
  no-undef: 1,
  react/jsx-one-expression-per-line: 1,
  react/jsx-tag-spacing: 1,
  padded-blocks: 1,
}
