name: project-check
on: push
jobs:
  checking:
    environment: testing
    env:
      REACT_APP_ACCESS_TOKEN: ${{ secrets.HEXLET_ID }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2

      - name: Installing node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        run: make install

      - name: Check ESLint
        run: make lint

      - name: Building
        run: make build
